import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import type { ToolAdapter } from './types.js';
import { compile } from '../core/compiler.js';

export const aiderAdapter: ToolAdapter = {
  name: 'aider',
  displayName: 'Aider',
  charBudget: 100_000,
  compress: false,
  configPaths: ['.aider.conf.yml', 'CONVENTIONS.md'],

  async generate({ rules, session, projectRoot }) {
    const output: Record<string, string> = {};

    // Generate CONVENTIONS.md with all rules + session
    const result = compile({
      session,
      rules,
      charBudget: this.charBudget,
      compress: false,
      toolName: this.name,
    });

    const conventionsPath = path.join(projectRoot, 'CONVENTIONS.md');
    output[conventionsPath] = `<!-- Generated by ai-context-bridge (ctx) -->\n\n` + result.content;

    // Generate or update .aider.conf.yml to reference CONVENTIONS.md
    const confPath = path.join(projectRoot, '.aider.conf.yml');
    let existingConf = '';
    try {
      existingConf = await fs.readFile(confPath, 'utf-8');
    } catch {
      // no existing config
    }

    if (!existingConf.includes('CONVENTIONS.md')) {
      const readDirective = `read:\n  - CONVENTIONS.md\n`;
      if (existingConf) {
        // Append to existing
        output[confPath] = existingConf.trimEnd() + '\n\n# Added by ctx\n' + readDirective;
      } else {
        output[confPath] = `# Generated by ai-context-bridge (ctx)\n${readDirective}`;
      }
    }

    return output;
  },

  async importExisting(projectRoot) {
    // Check for CONVENTIONS.md or .aider.conf.yml
    const conventionsPath = path.join(projectRoot, 'CONVENTIONS.md');
    try {
      const content = await fs.readFile(conventionsPath, 'utf-8');
      return content.replace(/^<!-- Generated by ai-context-bridge.*?-->\n*/s, '').trim() || null;
    } catch {
      return null;
    }
  },

  async detect() {
    try {
      const { execFile } = await import('node:child_process');
      const { promisify } = await import('node:util');
      await promisify(execFile)('aider', ['--version'], { timeout: 3000 });
      return true;
    } catch {
      return false;
    }
  },
};
