import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import type { ToolAdapter } from './types.js';
import { compile } from '../core/compiler.js';

export const antigravityAdapter: ToolAdapter = {
  name: 'antigravity',
  displayName: 'Antigravity (Google)',
  charBudget: 100_000,
  compress: false,
  configPaths: ['AGENTS.md', '.antigravity/'],

  async generate({ rules, session, projectRoot }) {
    const output: Record<string, string> = {};

    // Antigravity uses AGENTS.md (shared format with Codex) + its own .antigravity/ dir
    const result = compile({
      session,
      rules,
      charBudget: this.charBudget,
      compress: false,
      toolName: this.name,
    });

    const header = `<!-- Generated by ai-context-bridge (ctx) for Antigravity -->\n\n`;
    output[path.join(projectRoot, 'AGENTS.md')] = header + result.content;

    // Also write to .antigravity/ directory for tool-specific config
    const agDir = path.join(projectRoot, '.antigravity');
    await fs.mkdir(agDir, { recursive: true });

    // Write individual rule files
    for (const rule of rules) {
      const filename = `${String(rule.priority).padStart(2, '0')}-${rule.name}.md`;
      output[path.join(agDir, filename)] = rule.content;
    }

    // Session file
    if (session) {
      const sessionResult = compile({
        session,
        rules: [],
        charBudget: this.charBudget,
        compress: false,
        toolName: this.name,
      });
      output[path.join(agDir, '_session-resume.md')] = sessionResult.content;
    }

    return output;
  },

  async importExisting(projectRoot) {
    // Check .antigravity/ dir first, then AGENTS.md
    const agDir = path.join(projectRoot, '.antigravity');
    try {
      const files = await fs.readdir(agDir);
      const mdFiles = files.filter((f) => f.endsWith('.md') && !f.startsWith('_'));
      if (mdFiles.length > 0) {
        const parts: string[] = [];
        for (const file of mdFiles.sort()) {
          const content = await fs.readFile(path.join(agDir, file), 'utf-8');
          if (content.trim()) parts.push(`## ${file.replace('.md', '')}\n\n${content.trim()}`);
        }
        if (parts.length > 0) return parts.join('\n\n');
      }
    } catch {
      // no .antigravity dir
    }

    // Fallback to AGENTS.md
    const agentsMd = path.join(projectRoot, 'AGENTS.md');
    try {
      const content = await fs.readFile(agentsMd, 'utf-8');
      return content.replace(/^<!-- Generated by ai-context-bridge.*?-->\n*/s, '').trim() || null;
    } catch {
      return null;
    }
  },

  async detect() {
    try {
      const { execFile } = await import('node:child_process');
      const { promisify } = await import('node:util');
      // Try common Antigravity CLI commands
      await promisify(execFile)('antigravity', ['--version'], { timeout: 3000 });
      return true;
    } catch {
      return false;
    }
  },
};
