import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import type { ToolAdapter } from './types.js';
import { compile } from '../core/compiler.js';

export const claudeAdapter: ToolAdapter = {
  name: 'claude',
  displayName: 'Claude Code',
  charBudget: 100_000,
  compress: false,
  configPaths: ['CLAUDE.md'],

  async generate({ rules, session, projectRoot }) {
    const result = compile({
      session,
      rules,
      charBudget: this.charBudget,
      compress: false,
      toolName: this.name,
    });

    const header = `<!-- Generated by ai-context-bridge (ctx) — do not edit manually -->\n\n`;
    return {
      [path.join(projectRoot, 'CLAUDE.md')]: header + result.content,
    };
  },

  async importExisting(projectRoot) {
    const claudeMd = path.join(projectRoot, 'CLAUDE.md');
    try {
      const content = await fs.readFile(claudeMd, 'utf-8');
      // Strip auto-generated header if present
      return content.replace(/^<!-- Generated by ai-context-bridge.*?-->\n*/s, '').trim() || null;
    } catch {
      return null;
    }
  },

  async detect() {
    // Claude Code is a CLI, check if the command exists
    try {
      const { execFile } = await import('node:child_process');
      const { promisify } = await import('node:util');
      await promisify(execFile)('claude', ['--version'], { timeout: 3000 });
      return true;
    } catch {
      return false;
    }
  },
};
