import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import type { ToolAdapter } from './types.js';
import { compile } from '../core/compiler.js';

export const codexAdapter: ToolAdapter = {
  name: 'codex',
  displayName: 'OpenAI Codex CLI',
  charBudget: 32_768, // 32 KiB
  compress: false,
  configPaths: ['AGENTS.md'],

  async generate({ rules, session, projectRoot }) {
    const result = compile({
      session,
      rules,
      charBudget: this.charBudget,
      compress: false,
      toolName: this.name,
    });

    const header = `<!-- Generated by ai-context-bridge (ctx) -->\n\n`;
    return {
      [path.join(projectRoot, 'AGENTS.md')]: header + result.content,
    };
  },

  async importExisting(projectRoot) {
    const agentsMd = path.join(projectRoot, 'AGENTS.md');
    try {
      const content = await fs.readFile(agentsMd, 'utf-8');
      return content.replace(/^<!-- Generated by ai-context-bridge.*?-->\n*/s, '').trim() || null;
    } catch {
      return null;
    }
  },

  async detect() {
    try {
      const { execFile } = await import('node:child_process');
      const { promisify } = await import('node:util');
      await promisify(execFile)('codex', ['--version'], { timeout: 3000 });
      return true;
    } catch {
      return false;
    }
  },
};
