import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import type { ToolAdapter } from './types.js';
import { compile } from '../core/compiler.js';

export const copilotAdapter: ToolAdapter = {
  name: 'copilot',
  displayName: 'GitHub Copilot',
  charBudget: 200_000, // No hard limit, generous budget
  compress: false,
  configPaths: ['.github/copilot-instructions.md'],

  async generate({ rules, session, projectRoot }) {
    const result = compile({
      session,
      rules,
      charBudget: this.charBudget,
      compress: false,
      toolName: this.name,
    });

    const header = `<!-- Generated by ai-context-bridge (ctx) -->\n\n`;
    const ghDir = path.join(projectRoot, '.github');
    await fs.mkdir(ghDir, { recursive: true });

    return {
      [path.join(ghDir, 'copilot-instructions.md')]: header + result.content,
    };
  },

  async importExisting(projectRoot) {
    const instrPath = path.join(projectRoot, '.github', 'copilot-instructions.md');
    try {
      const content = await fs.readFile(instrPath, 'utf-8');
      return content.replace(/^<!-- Generated by ai-context-bridge.*?-->\n*/s, '').trim() || null;
    } catch {
      return null;
    }
  },

  async detect() {
    // Copilot is typically a VS Code extension, hard to detect CLI
    return false;
  },
};
