import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import type { ToolAdapter } from './types.js';
import { compile } from '../core/compiler.js';
import { yamlFrontmatter } from '../utils/markdown.js';

export const cursorAdapter: ToolAdapter = {
  name: 'cursor',
  displayName: 'Cursor',
  charBudget: 10_000, // ~2.5K per file recommended, multiple files
  compress: false,
  configPaths: ['.cursor/rules/'],

  async generate({ rules, session, projectRoot }) {
    const output: Record<string, string> = {};
    const rulesDir = path.join(projectRoot, '.cursor', 'rules');
    await fs.mkdir(rulesDir, { recursive: true });

    // Generate one .mdc file per rule
    for (const rule of rules) {
      const frontmatter = yamlFrontmatter({
        description: rule.name,
        globs: '**/*',
        alwaysApply: true,
      });
      const filename = `${String(rule.priority).padStart(2, '0')}-${rule.name}.mdc`;
      output[path.join(rulesDir, filename)] = frontmatter + '\n\n' + rule.content;
    }

    // Generate session resume file if there's a session
    if (session) {
      const result = compile({
        session,
        rules: [],
        charBudget: 2500,
        compress: false,
        toolName: this.name,
      });
      const frontmatter = yamlFrontmatter({
        description: 'Session resume context (auto-generated by ctx)',
        globs: '**/*',
        alwaysApply: true,
      });
      output[path.join(rulesDir, '_session-resume.mdc')] = frontmatter + '\n\n' + result.content;
    }

    return output;
  },

  async importExisting(projectRoot) {
    const rulesDir = path.join(projectRoot, '.cursor', 'rules');
    try {
      const files = await fs.readdir(rulesDir);
      const mdcFiles = files.filter((f) => f.endsWith('.mdc'));
      if (mdcFiles.length === 0) return null;

      const parts: string[] = [];
      for (const file of mdcFiles.sort()) {
        const content = await fs.readFile(path.join(rulesDir, file), 'utf-8');
        // Strip YAML frontmatter
        const stripped = content.replace(/^---[\s\S]*?---\n*/m, '').trim();
        if (stripped) parts.push(`## ${file.replace('.mdc', '')}\n\n${stripped}`);
      }
      return parts.join('\n\n') || null;
    } catch {
      return null;
    }

    // Also check .cursorrules (legacy)
  },

  async detect() {
    // Check if cursor CLI or app exists
    try {
      const { execFile } = await import('node:child_process');
      const { promisify } = await import('node:util');
      await promisify(execFile)('cursor', ['--version'], { timeout: 3000 });
      return true;
    } catch {
      return false;
    }
  },
};
